name: 'Terraform setup, Init, Validate, and Format Check'
description: >
  Setup Terraform and runs `terraform init`, `terraform validate`, and `terraform fmt -check -recursive`
  in sequence for a given working directory.

inputs:
  working-directory:
    description: 'Directory containing the Terraform configuration to run against'
    required: false
    default: '.'
  format-check-continue-on-error:
    description: 'Whether the workflow should continue if the format check fails'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform init

    - name: Terraform Validate
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform validate

    - name: Terraform Format Check
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: ${{ inputs.format-check-continue-on-error == 'true' }}
      run: terraform fmt -check -recursive
