name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'modules/azure/'
      - 'test/azure/*'

jobs:
  terraform_apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: "test/azure"
    env:
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      # ── Checkout ──
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Azure credentials
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ── Terraform workflow ──

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Plan
        run: |
          terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve

  terraform_destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: "test/azure"
    env:
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      # ── Checkout ──
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Azure credentials
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ── Terraform workflow ──

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Plan
        run: |
          terraform plan -destroy

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve
