name: Module test workflow for GCP

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'modules/gcp/*'
      - 'test/gcp/*'

concurrency:
  group: "gcp-module-test"
  cancel-in-progress: false

jobs:
  terraform_apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: "test/gcp"
    

    steps:
      # ── Checkout ──
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: GCP Login
        uses: ./.github/actions/gcp-login
        with:
          service-account-key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}
          credentials_json: ${{ inputs.credentials_json }}

      # ── Terraform workflow ──

      - name: Terraform Init, Validate, Format Check
        uses: ./.github/actions/terraform-init-validate-fmt
        with:
          working-directory: "test/gcp"

      - name: Terraform Plan
        run: |
          terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve

  terraform_destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    needs: terraform_apply
    if: github.run_attempt == success()
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: "test/gcp"

    steps:
      # ── Checkout ──
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: GCP Login
        uses: ./.github/actions/gcp-login
        with:
          service-account-key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}
          credentials_json: ${{ inputs.credentials_json }}
          

      # ── Terraform workflow ──

      - name: Terraform Init, Validate, Format Check
        uses: ./.github/actions/terraform-init-validate-fmt
        with:
          working-directory: "test/gcp"
          format-check-continue-on-error: "true"

      - name: Terraform Plan
        run: |
          terraform plan -destroy

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve
