name: Terraform init validate fmt

on:
  workflow_dispatch:

jobs:
  terraform_init_validate_fmt:
    name: "Terraform Init, Validate, and Format Check"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: "test/azure"

    steps:
      # ── Checkout ──
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: ./github/workflows/terraform-init.yml